export const carData = {
	name: 'Audi A3',
	description: 'Limousine40TDI qu./Sx S line/MATRIX/VITUAL',
	grossPrice: '23.999',
	netPrice: '20.167',
	rentPrice: '260',
	phone: '+380123456789',
	company: {
		name: 'Automobilhandelsgesellschaft Rodgau',
		banner:
			'https://img.classistatic.de/api/v1/mo-prod/images/8b/8b434fcc-b4b4-4234-bf03-b0ec4f20acb7?rule=mo-1600',
		logo: 'https://img.classistatic.de/api/v1/mo-prod/images/0d/0d479523-ed19-4e43-b571-ed305ef5210f?rule=mo-360',
	},
	stars: 5,
	location: {
		country: 'de',
		postalCode: 63110,
		city: 'Rodgau',
	},
	specs: [
		{ key: 'mileage', value: '116.188' },
		{ key: 'performance', value: '135 kW (184 PS)' },
		{ key: 'fuelType', value: 'Diesel' },
		{ key: 'gearbox', value: 'automatic' },
		{ key: 'initialRegistration', value: '04/2020' },
		{ key: 'vehicleOwner', value: 1 },
	],
	technicalDetails: [
		{ key: 'condition', value: 'Gebrauchtfahrzeug, Unfallfrei' },
		{ key: 'category', value: 'Limousine' },
		{ key: 'series', value: 'A3 Limousine (8VM)(04.2016->)' },
		{ key: 'equipmentLine', value: '40 TDI quattro sport' },
		{ key: 'mileage', value: '116.188 km' },
		{ key: 'engineCapacity', value: '1.968 cm³' },
		{ key: 'performance', value: '135 kW (184 PS)' },
		{ key: 'driveType', value: 'Verbrennungsmotor' },
		{ key: 'fuelType', value: 'Diesel' },
		{ key: 'energyConsumption', value: '5,2 l/100km' },
		{ key: 'co2Emissions', value: '138 g/km' },
		{ key: 'fuelConsumption', value: '5,2 l/100km (kombiniert)' },
		{ key: 'seats', value: 5 },
		{ key: 'doors', value: '4/5' },
		{ key: 'gearbox', value: 'Automatik' },
		{ key: 'emissionClass', value: 'Euro6d-TEMP' },
		{ key: 'environmentBadge', value: '4 (Grün)' },
		{ key: 'initialRegistration', value: '04/2020' },
		{ key: 'vehicleOwner', value: 1 },
		{ key: 'hu', value: 'Neu' },
		{ key: 'climateControl', value: '2-Zonen-Klimaautomatik' },
		{
			key: 'parkingAssist',
			value: 'Kamera, Vorne, Hinten, Selbstlenkende Systeme',
		},
		{ key: 'airbags', value: 'Front-, Seiten- und weitere Airbags' },
		{ key: 'manufacturerColor', value: 'MYTHOSSCHWARZ' },
		{ key: 'color', value: 'Schwarz Metallic' },
		{ key: 'interior', value: 'Vollleder, Schwarz' },
		{ key: 'trailerLoadBraked', value: '1.800 kg' },
		{ key: 'trailerLoadUnbraked', value: '750 kg' },
		{ key: 'weight', value: '1.555 kg' },
		{ key: 'cylinders', value: 4 },
		{ key: 'tankSize', value: '55 l' },
	],
	equipment: [
		'Abgedunkelte Scheiben',
		'ABS',
		'Adaptives Fahrwerk',
		'Adaptives Kurvenlicht',
		'Allradantrieb',
		'Ambiente-Beleuchtung',
		'Android Auto',
		'Apple CarPlay',
		'Armlehne',
		'Berganfahrassistent',
		'Blendfreies Fernlicht',
		'Bordcomputer',
		'CD-Spieler',
		'Elektr. Fensterheber',
		'Elektr. Seitenspiegel',
		'Elektr. Seitenspiegel anklappbar',
		'Elektr. Sitzeinstellung',
		'Elektr. Wegfahrsperre',
		'ESP',
		'Fernlichtassistent',
		'Freisprecheinrichtung',
		'Garantie',
		'Innenspiegel autom. abblendend',
		'Inspektion neu',
		'Isofix',
		'Lederlenkrad',
		'LED-Scheinwerfer',
		'LED-Tagfahrlicht',
		'Leichtmetallfelgen',
		'Lichtsensor',
		'Lordosenstütze',
		'Müdigkeitswarner',
		'Multifunktionslenkrad',
		'Musikstreaming integriert',
		'Navigationssystem',
		'Nebelscheinwerfer',
		'Nichtraucher-Fahrzeug',
		'Notrufsystem',
		'Pannenkit',
		'Partikelfilter',
		'Regensensor',
		'Reifendruckkontrolle',
		'Schaltwippen',
		'Scheckheftgepflegt',
		'Scheinwerferreinigung',
		'Schlüssellose Zentralverriegelung (Keyless)',
		'Servolenkung',
		'Sitzheizung',
		'Sommerreifen',
		'Soundsystem',
		'Sportfahrwerk',
		'Sportpaket',
		'Sportsitze',
		'Sprachsteuerung',
		'Start/Stopp-Automatik',
		'Tempomat',
		'Touchscreen',
		'Traktionskontrolle',
		'Umklappbarer Beifahrersitz',
		'USB',
		'Verkehrszeichenerkennung',
		'Volldigitales Kombiinstrument',
		'Zentralverriegelung',
	],
	images: [
		'https://img.classistatic.de/api/v1/mo-prod/images/30/307140de-e90c-4744-b6ad-b133cc2311a8?rule=mo-1600',
		'https://img.classistatic.de/api/v1/mo-prod/images/78/78a6d2b3-59a3-4c43-a088-b4cae6de9076?rule=mo-1600',
		'https://img.classistatic.de/api/v1/mo-prod/images/2f/2f35360f-6dcc-491a-8d6c-1c2f136a23bc?rule=mo-1600',
		'https://img.classistatic.de/api/v1/mo-prod/images/60/60f40e27-2669-4a2e-a0bf-55aae4787e9f?rule=mo-1600',
		'https://img.classistatic.de/api/v1/mo-prod/images/90/90406153-3e19-478f-9cab-dfd54376287a?rule=mo-1600',
	],
}
