export const carTechnicalDetails = {
	condition: { label: 'Fahrzeugzustand', modalType: 'condition' },
	category: { label: 'Kategorie' },
	series: { label: 'Baureihe' },
	equipmentLine: { label: 'Ausstattungslinie' },
	mileage: { label: 'Kilometerstand' },
	engineCapacity: { label: 'Hubraum' },
	performance: { label: 'Leistung' },
	driveType: { label: 'Antriebsart' },
	fuelType: { label: 'Kraftstoffart' },
	energyConsumption: {
		label: 'Energieverbrauch (komb.)',
		modalType: 'consumption',
	},
	co2Emissions: { label: 'CO₂-Emissionen (komb.)', modalType: 'c02-emissions' },
	fuelConsumption: {
		label: 'Kraftstoffverbrauch (komb.)',
	},
	seats: { label: 'Anzahl Sitzplätze' },
	doors: { label: 'Anzahl der Türen' },
	gearbox: { label: 'Getriebe' },
	emissionClass: { label: 'Schadstoffklasse', modalType: 'emissionClass' },
	environmentBadge: {
		label: 'Umweltplakette',
		modalType: 'environmentalBadge',
	},
	initialRegistration: { label: 'Erstzulassung' },
	vehicleOwner: { label: 'Anzahl der Fahrzeughalter' },
	hu: { label: 'HU' },
	climateControl: { label: 'Klimatisierung' },
	parkingAssist: { label: 'Einparkhilfe' },
	airbags: { label: 'Airbags' },
	manufacturerColor: { label: 'Farbe (Hersteller)' },
	color: { label: 'Farbe' },
	interior: { label: 'Innenausstattung' },
	trailerLoadBraked: { label: 'Anhängelast gebremst' },
	trailerLoadUnbraked: { label: 'Anhängelast ungebremst' },
	weight: { label: 'Gewicht' },
	cylinders: { label: 'Zylinder' },
	tankSize: { label: 'Tankgröße' },
}
